"""Render the publication-style predicted-vs-actual scatter plot.

Input is ``reports/results_comparison.csv`` generated by
``scripts/evaluate_final.py``. The output figure is used in the research
dossier and should be regenerated whenever the promoted evaluation CSV changes.
"""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Plot configuration.
sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)

CSV_PATH  = Path("reports/results_comparison.csv")
OUT_PATH  = Path("reports/final_coronium_scatter_tesis.png")

# Load evaluation data.
df = pd.read_csv(CSV_PATH)
y_real = df["Real_SSN"].values
y_pred = df["Predicted_SSN"].values

# Metrics reproduced from the CSV so the figure is self-contained.
residuals  = y_pred - y_real
mae        = float(np.mean(np.abs(residuals)))
rmse       = float(np.sqrt(np.mean(residuals ** 2)))
ss_res     = float(np.sum(residuals ** 2))
ss_tot     = float(np.sum((y_real - y_real.mean()) ** 2))
r2         = 1.0 - ss_res / ss_tot if ss_tot > 0 else float("nan")
nonzero    = y_real != 0.0
mape       = float(np.mean(np.abs(residuals[nonzero] / y_real[nonzero])) * 100) if nonzero.sum() > 0 else float("nan")

# Figure.
fig, ax = plt.subplots(figsize=(6.5, 6.5))

# Validation points.
ax.scatter(
    y_real, y_pred,
    color="#2e75b6", alpha=0.6, s=18,
    edgecolors="none", zorder=3,
    label=f"Validation samples (n={len(y_real):,})",
)

# Perfect-fit reference line: y = x.
lim_lo = min(y_real.min(), y_pred.min()) * 0.97
lim_hi = max(y_real.max(), y_pred.max()) * 1.03
ax.plot([lim_lo, lim_hi], [lim_lo, lim_hi],
        color="#c0392b", linestyle="--", linewidth=1.5, zorder=4, label="$y = x$ (perfect)")

# Identical square axes keep residual distance visually honest.
ax.set_xlim(lim_lo, lim_hi)
ax.set_ylim(lim_lo, lim_hi)
ax.set_aspect("equal", adjustable="box")

# Labels.
ax.set_xlabel("Ground-Truth Magnetic Index", labelpad=8)
ax.set_ylabel("Predicted Magnetic Index", labelpad=8)
ax.set_title(
    "Coronium V3 PRO - Final Hold-Out Performance\n"
    "(Predicted vs. Ground Truth, log-SI scale)",
    pad=12,
)

# Metrics box.
metrics_text = (
    f"MAE   = {mae:.4f}\n"
    f"RMSE  = {rmse:.4f}\n"
    f"MAPE  = {mape:.2f} %\n"
    f"R²    = {r2:.4f}"
)
ax.text(
    0.04, 0.96, metrics_text,
    transform=ax.transAxes,
    verticalalignment="top", horizontalalignment="left",
    fontsize=9.5, fontfamily="monospace",
    bbox=dict(
        boxstyle="round,pad=0.5",
        facecolor="white", alpha=0.85,
        edgecolor="#cccccc", linewidth=0.8,
    ),
    zorder=5,
)

ax.legend(fontsize=9, loc="lower right", framealpha=0.85)
ax.grid(True, alpha=0.35)

# Export.
OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
fig.savefig(OUT_PATH, dpi=300, bbox_inches="tight")
plt.close(fig)
print(f"Figure saved: {OUT_PATH}")
print(f"  MAE={mae:.4f}  RMSE={rmse:.4f}  R2={r2:.4f}  MAPE={mape:.2f}%")
